// Code generated by cmd/generate; DO NOT EDIT.

package cmd

import (
	"github.com/marketcalls/openalgo-cli/internal/api"
	"github.com/marketcalls/openalgo-cli/internal/cmdutil"
	"github.com/spf13/cobra"
)

var accountCmd = &cobra.Command{
	Use:   "account",
	Short: "Account funds, holdings, and margin",
	Long:  "View available funds and collateral, delivery holdings with P&L, and calculate margin for a basket of positions.",
}

var analyzerCmd = &cobra.Command{
	Use:   "analyzer",
	Short: "Analyzer (sandbox) mode",
	Long:  "Check or toggle analyzer mode, in which orders are routed to the sandbox instead of the live broker, and view sandbox P&L by symbol.",
}

var chartCmd = &cobra.Command{
	Use:   "chart",
	Short: "Chart workspace preferences",
	Long:  "Read and update the chart workspace preferences stored for the API key.",
}

var dataCmd = &cobra.Command{
	Use:   "data",
	Short: "Market data: quotes, depth, and history",
	Long:  "Real-time quotes and market depth, historical candles, and the intervals supported by the connected broker. For continuous updates use 'openalgo stream'.",
}

var gttCmd = &cobra.Command{
	Use:   "gtt",
	Short: "Manage GTT (Good Till Triggered) orders",
	Long:  "Place, modify, cancel, and list GTT triggers. SINGLE fires one child order when LTP crosses the trigger; OCO pairs a stoploss leg with a target leg.",
}

var marketCmd = &cobra.Command{
	Use:   "market",
	Short: "Market holidays and trading sessions",
	Long:  "List exchange holidays for a year and trading session times for a date.",
}

var optionCmd = &cobra.Command{
	Use:   "option",
	Short: "Options orders, symbols, chains, and Greeks",
	Long:  "Place options orders by strike offset (ATM, ITMn, OTMn), resolve option symbols, fetch option chains and synthetic futures, and calculate Black-76 Greeks.",
}

var orderCmd = &cobra.Command{
	Use:   "order",
	Short: "Place, modify, cancel, and list orders",
	Long:  "Place regular, smart (position-sized), basket, and split orders; modify or cancel open orders; view the order book, trade book, and order status. Orders carry --strategy openalgo-cli unless overridden.",
}

var pingCmd = &cobra.Command{
	Use:   "ping",
	Short: "Check that the API key resolves to an active broker session",
}

var positionCmd = &cobra.Command{
	Use:   "position",
	Short: "View and close positions",
	Long:  "List the day's positions, look up the net open quantity for one symbol, or square off every open position.",
}

var strategyCmd = &cobra.Command{
	Use:   "strategy",
	Short: "Manage OpenAlgo strategies and their runs",
	Long:  "List strategies, inspect configuration and runs, start or stop runs, close legs, and read the order and risk-event audit trail.",
}

var symbolCmd = &cobra.Command{
	Use:   "symbol",
	Short: "Look up symbols, expiries, and instruments",
	Long:  "Resolve symbol details from the master contract, search symbols, list expiry dates, and download the instrument master.",
}

var telegramCmd = &cobra.Command{
	Use:   "telegram",
	Short: "Telegram bot and notifications",
	Long:  "Configure, start, and stop the Telegram bot; list linked users; send notifications and broadcasts; manage per-user notification preferences.",
}

var telegramConfigCmd = &cobra.Command{
	Use:   "config",
	Short: "Telegram bot configuration",
}

var telegramPreferencesCmd = &cobra.Command{
	Use:   "preferences",
	Short: "Telegram user notification preferences",
}

var whatsappCmd = &cobra.Command{
	Use:   "whatsapp",
	Short: "WhatsApp notifications",
	Long:  "Send text, images, or documents through the paired WhatsApp device.",
}

var basketOrderCmd = fetchCmd("basket", api.BasketOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.BasketOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.BasketOrder(body)
})

var cancelAllOrderCmd = fetchCmd("cancel-all", api.CancelAllOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.CancelAllOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.CancelAllOrder(body)
})

var cancelGTTOrderCmd = fetchCmd("cancel", api.CancelGTTOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.CancelGTTOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.CancelGTTOrder(body)
})

var cancelOrderCmd = fetchCmd("cancel", api.CancelOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.CancelOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.CancelOrder(body)
})

var closePositionCmd = fetchCmd("close-all", api.ClosePositionOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.ClosePositionOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.ClosePosition(body)
})

var getAnalyzerStatusCmd = fetchCmd("status", api.GetAnalyzerStatusOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetAnalyzerStatus()
})

var getChartPreferencesCmd = fetchCmd("get", api.GetChartPreferencesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetChartPreferences()
})

var getDepthCmd = fetchCmd("depth", api.GetDepthOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetDepthOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetDepth(body)
})

var getExpiryCmd = fetchCmd("expiry", api.GetExpiryOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetExpiryOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetExpiry(body)
})

var getFundsCmd = fetchCmd("funds", api.GetFundsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetFunds()
})

var getGTTOrderbookCmd = fetchCmd("list", api.GetGTTOrderbookOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetGTTOrderbookOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetGTTOrderbook(body)
})

var getHistoryCmd = fetchCmd("history", api.GetHistoryOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetHistoryOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetHistory(body)
})

var getHoldingsCmd = fetchCmd("holdings", api.GetHoldingsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetHoldings()
})

var getInstrumentsCmd = fetchCmd("instruments", api.GetInstrumentsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetInstruments(queryFromFlags(cmd, api.GetInstrumentsOp))
})

var getIntervalsCmd = fetchCmd("intervals", api.GetIntervalsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetIntervals()
})

var getMarginCmd = fetchCmd("margin", api.GetMarginOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetMarginOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetMargin(body)
})

var getMarketHolidaysCmd = fetchCmd("holidays", api.GetMarketHolidaysOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetMarketHolidaysOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetMarketHolidays(body)
})

var getMarketTimingsCmd = fetchCmd("timings", api.GetMarketTimingsOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetMarketTimingsOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetMarketTimings(body)
})

var getMultiOptionGreeksCmd = fetchCmd("multi-greeks", api.GetMultiOptionGreeksOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetMultiOptionGreeksOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetMultiOptionGreeks(body)
})

var getMultiQuotesCmd = fetchCmd("quotes", api.GetMultiQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetMultiQuotesOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetMultiQuotes(body)
})

var getOpenPositionCmd = fetchCmd("get", api.GetOpenPositionOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetOpenPositionOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetOpenPosition(body)
})

var getOptionChainCmd = fetchCmd("chain", api.GetOptionChainOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetOptionChainOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetOptionChain(body)
})

var getOptionGreeksCmd = fetchCmd("greeks", api.GetOptionGreeksOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetOptionGreeksOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetOptionGreeks(body)
})

var getOptionSymbolCmd = fetchCmd("symbol", api.GetOptionSymbolOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetOptionSymbolOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetOptionSymbol(body)
})

var getOrderStatusCmd = fetchCmd("status", api.GetOrderStatusOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetOrderStatusOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetOrderStatus(body)
})

var getOrderbookCmd = fetchCmd("list", api.GetOrderbookOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetOrderbook()
})

var getPnlSymbolsCmd = fetchCmd("pnl", api.GetPnlSymbolsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetPnlSymbols()
})

var getPositionbookCmd = fetchCmd("list", api.GetPositionbookOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetPositionbook()
})

var getQuotesCmd = fetchCmd("quote", api.GetQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetQuotesOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetQuotes(body)
})

var getSymbolCmd = fetchCmd("get", api.GetSymbolOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetSymbolOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetSymbol(body)
})

var getSyntheticFutureCmd = fetchCmd("synthetic-future", api.GetSyntheticFutureOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.GetSyntheticFutureOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.GetSyntheticFuture(body)
})

var getTickerCmd = fetchCmd("ticker", api.GetTickerOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetTicker(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.GetTickerOp))
})

var getTradebookCmd = fetchCmd("trades", api.GetTradebookOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.GetTradebook()
})

var modifyGTTOrderCmd = fetchCmd("modify", api.ModifyGTTOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.ModifyGTTOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.ModifyGTTOrder(body)
})

var modifyOrderCmd = fetchCmd("modify", api.ModifyOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.ModifyOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.ModifyOrder(body)
})

var optionsMultiOrderCmd = fetchCmd("multi-order", api.OptionsMultiOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.OptionsMultiOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.OptionsMultiOrder(body)
})

var optionsOrderCmd = fetchCmd("order", api.OptionsOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.OptionsOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.OptionsOrder(body)
})

var placeGTTOrderCmd = fetchCmd("place", api.PlaceGTTOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.PlaceGTTOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.PlaceGTTOrder(body)
})

var placeOrderCmd = fetchCmd("place", api.PlaceOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.PlaceOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.PlaceOrder(body)
})

var placeSmartOrderCmd = fetchCmd("smart", api.PlaceSmartOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.PlaceSmartOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.PlaceSmartOrder(body)
})

var searchSymbolsCmd = fetchCmd("search", api.SearchSymbolsOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.SearchSymbolsOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.SearchSymbols(body)
})

var splitOrderCmd = fetchCmd("split", api.SplitOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.SplitOrderOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.SplitOrder(body)
})

var strategyCloseAllCmd = fetchCmd("close-all", api.StrategyCloseAllOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyCloseAllOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.StrategyCloseAll(body)
})

var strategyCloseLegCmd = fetchCmd("close-leg", api.StrategyCloseLegOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyCloseLegOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.StrategyCloseLeg(body)
})

var strategyEventsCmd = fetchCmd("events", api.StrategyEventsOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyEventsOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.StrategyEvents(body)
})

var strategyListCmd = fetchCmd("list", api.StrategyListOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyListOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.StrategyList(body)
})

var strategyOrdersCmd = fetchCmd("orders", api.StrategyOrdersOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyOrdersOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.StrategyOrders(body)
})

var strategyRunsCmd = fetchCmd("runs", api.StrategyRunsOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyRunsOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.StrategyRuns(body)
})

var strategyStartCmd = fetchCmd("start", api.StrategyStartOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyStartOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.StrategyStart(body)
})

var strategyStatusCmd = fetchCmd("status", api.StrategyStatusOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyStatusOp)
	if err != nil {
		return nil, err
	}
	return openalgoClient.StrategyStatus(body)
})

var strategyStopCmd = fetchCmd("stop", api.StrategyStopOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.StrategyStopOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.StrategyStop(body)
})

var telegramBroadcastCmd = fetchCmd("broadcast", api.TelegramBroadcastOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.TelegramBroadcastOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.TelegramBroadcast(body)
})

var telegramGetConfigCmd = fetchCmd("get", api.TelegramGetConfigOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.TelegramGetConfig()
})

var telegramGetPreferencesCmd = fetchCmd("get", api.TelegramGetPreferencesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.TelegramGetPreferences(queryFromFlags(cmd, api.TelegramGetPreferencesOp))
})

var telegramNotifyCmd = fetchCmd("notify", api.TelegramNotifyOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.TelegramNotifyOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.TelegramNotify(body)
})

var telegramSetConfigCmd = fetchCmd("set", api.TelegramSetConfigOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.TelegramSetConfigOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.TelegramSetConfig(body)
})

var telegramSetPreferencesCmd = fetchCmd("set", api.TelegramSetPreferencesOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.TelegramSetPreferencesOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.TelegramSetPreferences(body)
})

var telegramStartCmd = fetchCmd("start", api.TelegramStartOp, func(cmd *cobra.Command, args []string) (any, error) {
	if cmdutil.Bool(cmd, "dry-run") {
		return map[string]any{}, nil
	}
	return openalgoClient.TelegramStart()
})

var telegramStatsCmd = fetchCmd("stats", api.TelegramStatsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.TelegramStats(queryFromFlags(cmd, api.TelegramStatsOp))
})

var telegramStopCmd = fetchCmd("stop", api.TelegramStopOp, func(cmd *cobra.Command, args []string) (any, error) {
	if cmdutil.Bool(cmd, "dry-run") {
		return map[string]any{}, nil
	}
	return openalgoClient.TelegramStop()
})

var telegramUsersCmd = fetchCmd("users", api.TelegramUsersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return openalgoClient.TelegramUsers(queryFromFlags(cmd, api.TelegramUsersOp))
})

var toggleAnalyzerCmd = fetchCmd("toggle", api.ToggleAnalyzerOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.ToggleAnalyzerOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.ToggleAnalyzer(body)
})

var updateChartPreferencesCmd = fetchCmd("set", api.UpdateChartPreferencesOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.UpdateChartPreferencesOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.UpdateChartPreferences(body)
})

var whatsAppNotifyCmd = fetchCmd("notify", api.WhatsAppNotifyOp, func(cmd *cobra.Command, args []string) (any, error) {
	body, err := bodyFromFlags(cmd, api.WhatsAppNotifyOp)
	if err != nil {
		return nil, err
	}
	if cmdutil.Bool(cmd, "dry-run") {
		return body, nil
	}
	return openalgoClient.WhatsAppNotify(body)
})

func init() {
	attachCmd(pingCmd, api.PingOp, func(cmd *cobra.Command, args []string) (any, error) {
		return openalgoClient.Ping()
	})

	telegramCmd.AddCommand(telegramConfigCmd)
	telegramCmd.AddCommand(telegramPreferencesCmd)

	orderCmd.AddCommand(basketOrderCmd)
	orderCmd.AddCommand(cancelAllOrderCmd)
	gttCmd.AddCommand(cancelGTTOrderCmd)
	orderCmd.AddCommand(cancelOrderCmd)
	positionCmd.AddCommand(closePositionCmd)
	analyzerCmd.AddCommand(getAnalyzerStatusCmd)
	chartCmd.AddCommand(getChartPreferencesCmd)
	dataCmd.AddCommand(getDepthCmd)
	symbolCmd.AddCommand(getExpiryCmd)
	accountCmd.AddCommand(getFundsCmd)
	gttCmd.AddCommand(getGTTOrderbookCmd)
	dataCmd.AddCommand(getHistoryCmd)
	accountCmd.AddCommand(getHoldingsCmd)
	symbolCmd.AddCommand(getInstrumentsCmd)
	dataCmd.AddCommand(getIntervalsCmd)
	accountCmd.AddCommand(getMarginCmd)
	marketCmd.AddCommand(getMarketHolidaysCmd)
	marketCmd.AddCommand(getMarketTimingsCmd)
	optionCmd.AddCommand(getMultiOptionGreeksCmd)
	dataCmd.AddCommand(getMultiQuotesCmd)
	positionCmd.AddCommand(getOpenPositionCmd)
	optionCmd.AddCommand(getOptionChainCmd)
	optionCmd.AddCommand(getOptionGreeksCmd)
	optionCmd.AddCommand(getOptionSymbolCmd)
	orderCmd.AddCommand(getOrderStatusCmd)
	orderCmd.AddCommand(getOrderbookCmd)
	analyzerCmd.AddCommand(getPnlSymbolsCmd)
	positionCmd.AddCommand(getPositionbookCmd)
	dataCmd.AddCommand(getQuotesCmd)
	symbolCmd.AddCommand(getSymbolCmd)
	optionCmd.AddCommand(getSyntheticFutureCmd)
	dataCmd.AddCommand(getTickerCmd)
	orderCmd.AddCommand(getTradebookCmd)
	gttCmd.AddCommand(modifyGTTOrderCmd)
	orderCmd.AddCommand(modifyOrderCmd)
	optionCmd.AddCommand(optionsMultiOrderCmd)
	optionCmd.AddCommand(optionsOrderCmd)
	gttCmd.AddCommand(placeGTTOrderCmd)
	orderCmd.AddCommand(placeOrderCmd)
	orderCmd.AddCommand(placeSmartOrderCmd)
	symbolCmd.AddCommand(searchSymbolsCmd)
	orderCmd.AddCommand(splitOrderCmd)
	strategyCmd.AddCommand(strategyCloseAllCmd)
	strategyCmd.AddCommand(strategyCloseLegCmd)
	strategyCmd.AddCommand(strategyEventsCmd)
	strategyCmd.AddCommand(strategyListCmd)
	strategyCmd.AddCommand(strategyOrdersCmd)
	strategyCmd.AddCommand(strategyRunsCmd)
	strategyCmd.AddCommand(strategyStartCmd)
	strategyCmd.AddCommand(strategyStatusCmd)
	strategyCmd.AddCommand(strategyStopCmd)
	telegramCmd.AddCommand(telegramBroadcastCmd)
	telegramConfigCmd.AddCommand(telegramGetConfigCmd)
	telegramPreferencesCmd.AddCommand(telegramGetPreferencesCmd)
	telegramCmd.AddCommand(telegramNotifyCmd)
	telegramConfigCmd.AddCommand(telegramSetConfigCmd)
	telegramPreferencesCmd.AddCommand(telegramSetPreferencesCmd)
	telegramCmd.AddCommand(telegramStartCmd)
	telegramCmd.AddCommand(telegramStatsCmd)
	telegramCmd.AddCommand(telegramStopCmd)
	telegramCmd.AddCommand(telegramUsersCmd)
	analyzerCmd.AddCommand(toggleAnalyzerCmd)
	chartCmd.AddCommand(updateChartPreferencesCmd)
	whatsappCmd.AddCommand(whatsAppNotifyCmd)
}
